src/java/entity/Book.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entity;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author viquy
 */
@Entity
@Table(name = "Book")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Book.findAll", query = "SELECT b FROM Book b")
    , @NamedQuery(name = "Book.findByBookID", query = "SELECT b FROM Book b WHERE b.bookID = :bookID")
    , @NamedQuery(name = "Book.findByBookName", query = "SELECT b FROM Book b WHERE b.bookName = :bookName")
    , @NamedQuery(name = "Book.findByBookDes", query = "SELECT b FROM Book b WHERE b.bookDes = :bookDes")
    , @NamedQuery(name = "Book.findByBookIMG", query = "SELECT b FROM Book b WHERE b.bookIMG = :bookIMG")
    , @NamedQuery(name = "Book.findByBookfile", query = "SELECT b FROM Book b WHERE b.bookfile = :bookfile")
    , @NamedQuery(name = "Book.findByBookstatus", query = "SELECT b FROM Book b WHERE b.bookstatus = :bookstatus")})
public class Book implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 250)
    @Column(name = "bookID")
    private String bookID;
    @Size(max = 250)
    @Column(name = "bookName")
    private String bookName;
    @Size(max = 250)
    @Column(name = "bookDes")
    private String bookDes;
    @Size(max = 250)
    @Column(name = "bookIMG")
    private String bookIMG;
    @Size(max = 250)
    @Column(name = "bookfile")
    private String bookfile;
    @Size(max = 1)
    @Column(name = "bookstatus")
    private String bookstatus;
    @JoinColumn(name = "authorID", referencedColumnName = "authorID")
    @ManyToOne
    private Author authorID;
    @JoinColumn(name = "categoryID", referencedColumnName = "categoryID")
    @ManyToOne
    private Category categoryID;
    @JoinColumn(name = "producerID", referencedColumnName = "producerID")
    @ManyToOne
    private Producer producerID;

    public Book() {
    }

    public Book(String bookID) {
        this.bookID = bookID;
    }

    public String getBookID() {
        return bookID;
    }

    public void setBookID(String bookID) {
        this.bookID = bookID;
    }

    public String getBookName() {
        return bookName;
    }

    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    public String getBookDes() {
        return bookDes;
    }

    public void setBookDes(String bookDes) {
        this.bookDes = bookDes;
    }

    public String getBookIMG() {
        return bookIMG;
    }

    public void setBookIMG(String bookIMG) {
        this.bookIMG = bookIMG;
    }

    public String getBookfile() {
        return bookfile;
    }

    public void setBookfile(String bookfile) {
        this.bookfile = bookfile;
    }

    public String getBookstatus() {
        return bookstatus;
    }

    public void setBookstatus(String bookstatus) {
        this.bookstatus = bookstatus;
    }

    public Author getAuthorID() {
        return authorID;
    }

    public void setAuthorID(Author authorID) {
        this.authorID = authorID;
    }

    public Category getCategoryID() {
        return categoryID;
    }

    public void setCategoryID(Category categoryID) {
        this.categoryID = categoryID;
    }

    public Producer getProducerID() {
        return producerID;
    }

    public void setProducerID(Producer producerID) {
        this.producerID = producerID;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (bookID != null ? bookID.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Book)) {
            return false;
        }
        Book other = (Book) object;
        if ((this.bookID == null && other.bookID != null) || (this.bookID != null && !this.bookID.equals(other.bookID))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entity.Book[ bookID=" + bookID + " ]";
    }
    
}

src/java/beanmanager/BookController.java
package beanmanager;

import entity.Book;
import beanmanager.util.JsfUtil;
import beanmanager.util.JsfUtil.PersistAction;
import session.BookFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("bookController")
@SessionScoped
public class BookController implements Serializable {

    @EJB
    private session.BookFacade ejbFacade;
    private List<Book> items = null;
    private Book selected;

    public BookController() {
    }

    public Book getSelected() {
        return selected;
    }

    public void setSelected(Book selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private BookFacade getFacade() {
        return ejbFacade;
    }

    public Book prepareCreate() {
        selected = new Book();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("BookCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("BookUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("BookDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Book> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Book getBook(java.lang.String id) {
        return getFacade().find(id);
    }

    public List<Book> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Book> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Book.class)
    public static class BookControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            BookController controller = (BookController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "bookController");
            return controller.getBook(getKey(value));
        }

        java.lang.String getKey(String value) {
            java.lang.String key;
            key = value;
            return key;
        }

        String getStringKey(java.lang.String value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Book) {
                Book o = (Book) object;
                return getStringKey(o.getBookID());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Book.class.getName()});
                return null;
            }
        }

    }

}

web/book/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="BookCreateDlg" widgetVar="BookCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateBookTitle}">
            <h:form id="BookCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{bookController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateBookLabel_bookID}" for="bookID" />
                        <p:inputText id="bookID" value="#{bookController.selected.bookID}" title="#{bundle.CreateBookTitle_bookID}" required="true" requiredMessage="#{bundle.CreateBookRequiredMessage_bookID}"/>
                        <p:outputLabel value="#{bundle.CreateBookLabel_bookName}" for="bookName" />
                        <p:inputText id="bookName" value="#{bookController.selected.bookName}" title="#{bundle.CreateBookTitle_bookName}" />
                        <p:outputLabel value="#{bundle.CreateBookLabel_bookDes}" for="bookDes" />
                        <p:inputText id="bookDes" value="#{bookController.selected.bookDes}" title="#{bundle.CreateBookTitle_bookDes}" />
                        <p:outputLabel value="#{bundle.CreateBookLabel_bookIMG}" for="bookIMG" />
                        <p:inputText id="bookIMG" value="#{bookController.selected.bookIMG}" title="#{bundle.CreateBookTitle_bookIMG}" />
                        <p:outputLabel value="#{bundle.CreateBookLabel_bookfile}" for="bookfile" />
                        <p:inputText id="bookfile" value="#{bookController.selected.bookfile}" title="#{bundle.CreateBookTitle_bookfile}" />
                        <p:outputLabel value="#{bundle.CreateBookLabel_bookstatus}" for="bookstatus" />
                        <p:inputText id="bookstatus" value="#{bookController.selected.bookstatus}" title="#{bundle.CreateBookTitle_bookstatus}" />
                        <p:outputLabel value="#{bundle.CreateBookLabel_authorID}" for="authorID" />
                        <p:selectOneMenu id="authorID" value="#{bookController.selected.authorID}" >
                            <f:selectItems value="#{authorController.itemsAvailableSelectOne}"
                                           var="authorIDItem"
                                           itemValue="#{authorIDItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateBookLabel_categoryID}" for="categoryID" />
                        <p:selectOneMenu id="categoryID" value="#{bookController.selected.categoryID}" >
                            <f:selectItems value="#{categoryController.itemsAvailableSelectOne}"
                                           var="categoryIDItem"
                                           itemValue="#{categoryIDItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateBookLabel_producerID}" for="producerID" />
                        <p:selectOneMenu id="producerID" value="#{bookController.selected.producerID}" >
                            <f:selectItems value="#{producerController.itemsAvailableSelectOne}"
                                           var="producerIDItem"
                                           itemValue="#{producerIDItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{bookController.create}" value="#{bundle.Save}" update="display,:BookListForm:datalist,:growl" oncomplete="handleSubmit(args,'BookCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="BookCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/book/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="BookEditDlg" widgetVar="BookEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditBookTitle}">
            <h:form id="BookEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{bookController.selected != null}">
                        <p:outputLabel value="#{bundle.EditBookLabel_bookID}" for="bookID" />
                        <p:inputText id="bookID" value="#{bookController.selected.bookID}" title="#{bundle.EditBookTitle_bookID}" required="true" requiredMessage="#{bundle.EditBookRequiredMessage_bookID}"/>
                        <p:outputLabel value="#{bundle.EditBookLabel_bookName}" for="bookName" />
                        <p:inputText id="bookName" value="#{bookController.selected.bookName}" title="#{bundle.EditBookTitle_bookName}" />
                        <p:outputLabel value="#{bundle.EditBookLabel_bookDes}" for="bookDes" />
                        <p:inputText id="bookDes" value="#{bookController.selected.bookDes}" title="#{bundle.EditBookTitle_bookDes}" />
                        <p:outputLabel value="#{bundle.EditBookLabel_bookIMG}" for="bookIMG" />
                        <p:inputText id="bookIMG" value="#{bookController.selected.bookIMG}" title="#{bundle.EditBookTitle_bookIMG}" />
                        <p:outputLabel value="#{bundle.EditBookLabel_bookfile}" for="bookfile" />
                        <p:inputText id="bookfile" value="#{bookController.selected.bookfile}" title="#{bundle.EditBookTitle_bookfile}" />
                        <p:outputLabel value="#{bundle.EditBookLabel_bookstatus}" for="bookstatus" />
                        <p:inputText id="bookstatus" value="#{bookController.selected.bookstatus}" title="#{bundle.EditBookTitle_bookstatus}" />
                        <p:outputLabel value="#{bundle.EditBookLabel_authorID}" for="authorID" />
                        <p:selectOneMenu id="authorID" value="#{bookController.selected.authorID}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{authorController.itemsAvailableSelectOne}"
                                           var="authorIDItem"
                                           itemValue="#{authorIDItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditBookLabel_categoryID}" for="categoryID" />
                        <p:selectOneMenu id="categoryID" value="#{bookController.selected.categoryID}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{categoryController.itemsAvailableSelectOne}"
                                           var="categoryIDItem"
                                           itemValue="#{categoryIDItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditBookLabel_producerID}" for="producerID" />
                        <p:selectOneMenu id="producerID" value="#{bookController.selected.producerID}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{producerController.itemsAvailableSelectOne}"
                                           var="producerIDItem"
                                           itemValue="#{producerIDItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{bookController.update}" value="#{bundle.Save}" update="display,:BookListForm:datalist,:growl" oncomplete="handleSubmit(args, 'BookEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="BookEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/book/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListBookTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="BookListForm">
                <p:panel header="#{bundle.ListBookTitle}">
                    <p:dataTable id="datalist" value="#{bookController.items}" var="item"
                                 selectionMode="single" selection="#{bookController.selected}"
                                 paginator="true"
                                 rowKey="#{item.bookID}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBookTitle_bookID}"/>
                            </f:facet>
                            <h:outputText value="#{item.bookID}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBookTitle_bookName}"/>
                            </f:facet>
                            <h:outputText value="#{item.bookName}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBookTitle_bookDes}"/>
                            </f:facet>
                            <h:outputText value="#{item.bookDes}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBookTitle_bookIMG}"/>
                            </f:facet>
                            <h:outputText value="#{item.bookIMG}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBookTitle_bookfile}"/>
                            </f:facet>
                            <h:outputText value="#{item.bookfile}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBookTitle_bookstatus}"/>
                            </f:facet>
                            <h:outputText value="#{item.bookstatus}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBookTitle_authorID}"/>
                            </f:facet>
                            <h:outputText value="#{item.authorID}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBookTitle_categoryID}"/>
                            </f:facet>
                            <h:outputText value="#{item.categoryID}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBookTitle_producerID}"/>
                            </f:facet>
                            <h:outputText value="#{item.producerID}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{bookController.prepareCreate}" update=":BookCreateForm" oncomplete="PF('BookCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":BookViewForm" oncomplete="PF('BookViewDialog').show()" disabled="#{empty bookController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":BookEditForm" oncomplete="PF('BookEditDialog').show()" disabled="#{empty bookController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{bookController.destroy}" update=":growl,datalist" disabled="#{empty bookController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/book/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="BookViewDlg" widgetVar="BookViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewBookTitle}">
            <h:form id="BookViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{bookController.selected != null}">
                        <h:outputText value="#{bundle.ViewBookLabel_bookID}"/>
                        <h:outputText value="#{bookController.selected.bookID}" title="#{bundle.ViewBookTitle_bookID}"/>
                        <h:outputText value="#{bundle.ViewBookLabel_bookName}"/>
                        <h:outputText value="#{bookController.selected.bookName}" title="#{bundle.ViewBookTitle_bookName}"/>
                        <h:outputText value="#{bundle.ViewBookLabel_bookDes}"/>
                        <h:outputText value="#{bookController.selected.bookDes}" title="#{bundle.ViewBookTitle_bookDes}"/>
                        <h:outputText value="#{bundle.ViewBookLabel_bookIMG}"/>
                        <h:outputText value="#{bookController.selected.bookIMG}" title="#{bundle.ViewBookTitle_bookIMG}"/>
                        <h:outputText value="#{bundle.ViewBookLabel_bookfile}"/>
                        <h:outputText value="#{bookController.selected.bookfile}" title="#{bundle.ViewBookTitle_bookfile}"/>
                        <h:outputText value="#{bundle.ViewBookLabel_bookstatus}"/>
                        <h:outputText value="#{bookController.selected.bookstatus}" title="#{bundle.ViewBookTitle_bookstatus}"/>
                        <h:outputText value="#{bundle.ViewBookLabel_authorID}"/>
                        <h:outputText value="#{bookController.selected.authorID}" title="#{bundle.ViewBookTitle_authorID}"/>
                        <h:outputText value="#{bundle.ViewBookLabel_categoryID}"/>
                        <h:outputText value="#{bookController.selected.categoryID}" title="#{bundle.ViewBookTitle_categoryID}"/>
                        <h:outputText value="#{bundle.ViewBookLabel_producerID}"/>
                        <h:outputText value="#{bookController.selected.producerID}" title="#{bundle.ViewBookTitle_producerID}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="BookViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>